language: ruby
dist: trusty
sudo: required
install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh
  - helm init -c
  - helm plugin install https://github.com/technosophos/helm-template
  - wget https://github.com/garethr/kubetest/releases/download/0.1.1/kubetest-linux-amd64.tar.gz && tar xf kubetest-linux-amd64.tar.gz && mv kubetest /usr/local/bin

script:
  - cd helm-chart/web-api
  - ../scripts/test.sh
