team: helm-demo
nameOverride: httpd
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - httpd.local
image:
  repository: local
  version: 1
service:
  internalPort: 13337
  isAlivePath: /lol.html